# 分类格式:
#   分类名称:
#     - title: "填写标题"
#       description: "填写描述"
#       type: "link"
#       url: "填写跳转的 url"
#       pinned: true  # 是否置顶

favorites:
  AI/AI产品:
    - title: Qwen
      description: "通义千问的官方网站"
      type: link
      url: https://chat.qwen.ai/
      pinned: true
    - title: 腾讯元宝 - 轻松工作 多点生活
      description: ""
      type: link
      url: https://yuanbao.tencent.com/
    - title: 文心一言
      description: ""
      type: link
      url: https://yiyan.baidu.com/
    - title: 通义千问
      description: ""
      type: link
      url: https://tongyi.aliyun.com/
    - title: Claude
      description: " "
      type: link
      url: https://chat.claudeai.ai/chats
    - title: 天工AI搜索 — 知识从这里开始
      description: ""
      type: link
      url: https://search.tiangong.cn/
    - title: DeepSeek - 探索未至之境
      description: ""
      type: link
      url: https://chat.deepseek.com/
    - title: Kimi.ai - 帮你看更大的世界
      description: ""
      type: link
      url: https://kimi.moonshot.cn/
    - title: AI Chat
      description: ""
      type: link
      url: https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1
    - title: flowith 2.0 - Your AI Creation Workspace, with Knowledge
      description: "flowith 是一个AI创作工作空间，支持知识库、AI绘画、AI写作、AI代码、AI翻译、AI语音、AI视频、AI音频、AI图片、AI文档、AI表格、AI幻灯片、AI思维导图、AI流程图、AIUML、AIERD、AI项目管理、AI项目计划、AI项目进度、AI项目风险、AI项目质量、AI项目成本、AI项目收益、AI项目风险、AI项目质量、AI项目成本、AI项目收益"
      type: link
      url: https://flowith.net
    - title: 豆包 - 字节跳动旗下 AI 智能助手
      description: ""
      type: link
      url: https://www.doubao.com/chat/
    - title: 腾讯元器
      description: ""
      type: link
      url: https://yuanqi.tencent.com/agent-shop
    - title: Doc2X
      description: ""
      type: link
      url: https://doc2x.noedgeai.com/
    - title: 概览 · 魔搭社区
      description: ""
      type: link
      url: https://modelscope.cn/my/overview
    - title: 火山引擎-云上增长新动力
      description: ""
      type: link
      url: https://www.volcengine.com/
    - title: 安装 | Cursor文档-Cursor中文文档-Cursor AI文档
      description: ""
      type: link
      url: https://cursordocs.com/docs/get-started/installation
    - title: ima.copilot-腾讯智能工作台
      description: ""
      type: link
      url: https://ima.qq.com/
    - title: 上传图片 – remove.bg
      description: ""
      type: link
      url: https://www.remove.bg/zh/upload
    - title: 主页 - 扣子
      description: ""
      type: link
      url: https://www.coze.cn/home
    - title: coreml-community (Core ML Models)
      description: ""
      type: link
      url: https://huggingface.co/coreml-community
    - title: LobeHub
      description: "LobeChat：个人 LLM 效能工具，超越 ChatGPT / OLLaMA 使用体验"
      type: link
      url: https://lobehub.com/zh
    - title: 飞书知识问答
      description: ""
      type: link
      url: https://ask.feishu.cn/guest
    - title: Monica - 万能的助手，懂你的伙伴
      description: ""
      type: link
      url: https://monica.cn/home
    - title: Smithery - Model Context Protocol Registry
      description: ""
      type: link
      url: https://smithery.ai/
    - title: 纳米AI - 大模型
      description: ""
      type: link
      url: https://bot.n.cn/?src=AIsearch
    - title: 笔杆论文写作_首页
      description: ""
      type: link
      url: https://write.bigan.net/#/home
    - title: SurveyGO
      description: ""
      type: link
      url: https://surveygo.modelbest.cn/
    - title: 觅果·Migo AI 创新加速平台
      description: ""
      type: link
      url: https://migo.intern-ai.org.cn/education
  AI/AI工具:
    - title: "Dify 工作室"
      description: "Dify 云平台，提供 AI 应用开发、部署和管理的一站式解决方案。"
      type: "link"
      url: "https://cloud.dify.ai/apps"
    - title: BISHENG
      description: ""
      type: link
      url: https://bisheng.dataelem.com/
    - title: "MinerU"
      description: "MinerU 免费全能的文档解析神器"
      type: "link"
      url: "https://mineru.net/"
    - title: MinerU Documentation
      description: ""
      type: link
      url: https://mineru.readthedocs.io/en/latest/index.html
    - title: Napkin AI
      description: "Napkin AI 是一款专注于商业故事可视化的智能工具，旨在通过AI技术将文本内容自动转化为专业级视觉作品，帮助用户高效传达想法"
      type: link
      url: https://napkin.ai/
      pinned: true
    - title: DeepSeek 模型兼容性检测
      description: ""
      type: link
      url: https://tools.thinkinai.xyz/
    - title: AIGC 提示词可视化编辑器 | OPS | Open Prompt Studio
      description: ""
      type: link
      url: https://moonvy.com/apps/ops/
    - title: Prompt House
      description: ""
      type: link
      url: https://prompthouse.app/
    - title: MCP 广场 · 魔搭社区
      description: ""
      type: link
      url: https://www.modelscope.cn/mcp
    - title: MCP Servers
      description: ""
      type: link
      url: https://mcp.so
    - title: MCPServer -Discover Exceptional MCP Servers
      description: ""
      type: link
      url: https://mcpsvr.com/
    - title: remove.bg
      description: "在线抠图软件_图片去除背景"
      type: link
      url: https://www.remove.bg/zh
    - title: AILongAI工具箱
      description: ""
      type: link
      url: https://www.ailongtime.com/
    - title: 路导 ludao 的个人说明书｜知识库 Index - 飞书云文档
      description: ""
      type: link
      url: https://v0qy0enn8r.feishu.cn/wiki/WckZwKa26iL2N3kRUD4coeCJnZc
    - title: LangChain中文网 - 跟着LangChain学AI开发
      description: ""
      type: link
      url: https://www.langchain.com.cn/
    - title: prompts.chat — awesome AI prompts
      description: ""
      type: link
      url: https://prompts.chat/
  AI/AI开放平台:
    - title: DeepSeek 开放平台
      description: ""
      type: link
      url: https://platform.deepseek.com/usage
    - title: AIbase - 智能匹配最适合您的AI产品和网站
      description: ""
      type: link
      url: https://top.aibase.com/
    - title: SiliconCloud-硅基流动
      description: ""
      type: link
      url: https://cloud.siliconflow.cn/models
    - title: OpenRouter
      description: ""
      type: link
      url: https://openrouter.ai/
    - title: 百炼控制台
      description: ""
      type: link
      url: https://bailian.console.aliyun.com/#/home
    - title: Ollama
      description: "Ollama 是一个开源的AI模型库，支持多种AI模型"
      type: link
      url: https://ollama.com/
  AI/AIGC:
    - title: 通义万相
      description: ""
      type: link
      url: https://tongyi.aliyun.com/wanxiang/creation
    - title: Civitai | Stable Diffusion models, embeddings, hypernetworks and more
      description: ""
      type: link
      url: https://civitai.com/
    - title: 【AI繪畫】Stable-Diffusion 通過骨架分析插件ControlNet 來製作超有意境的圖片 - 零度解說
      description: ""
      type: link
      url: https://www.freedidi.com/8474.html
    - title: Stable Diffusion 法术解析
      description: ""
      type: link
      url: https://spell.novelai.dev/
  Dev/云服务:
    - title: 腾讯云-EdgeOne服务
      description: "腾讯云EdgeOne是一款集安全加速、智能调度和边缘计算于一体的全球边缘云服务平台。"
      type: link
      url: https://console.cloud.tencent.com/edgeone/pages
      pinned: true
    - title: cloudflare
      description: "Cloudflare 是一家提供内容分发网络 (CDN)、DDoS 防护、域名系统 (DNS) 解析等服务的网络安全和性能优化公司。"
      type: link
      url: https://www.cloudflare.com/
      pinned: true
    - title: Vercel
      description: "Vercel 是一个全栈云平台，用于构建和部署现代 Web 应用程序。"
      type: link
      url: https://vercel.com/
      pinned: true
    - title: Supabase
      description: "Supabase 是一个开源的 Firebase 替代品，提供实时数据库、身份验证、文件存储等功能。"
      type: link
      url: https://supabase.com/
      pinned: true
  Dev/开发工具:
    - title: "GitHub"
      description: "全球最大的代码托管平台，提供Git版本控制和协作开发功能"
      type: "link"
      url: "https://github.com"
      pinned: true
    - title: "Project Graph 在线绘图"
      description: "快速绘制节点图的桌面工具，可以用于项目进程拓扑图绘制、快速头脑风暴草稿。"
      type: "link"
      url: "https://web.project-graph.top/"
    - title: "Mermaid 在线编辑器"
      description: "基于 JavaScript 的图表工具，可渲染 Markdown 启发的文本定义以动态创建和修改图表。"
      type: "link"
      url: "https://mermaid.live/edit"
    - title: "draw.io"
      description: "draw.io 是一款在线的流程图绘制工具，支持流程图、思维导图、UML 图等多种图表类型。"
      type: "link"
      url: "https://app.diagrams.net/"
    - title: "tldraw"
      description: "画图软件"
      type: link
      url: https://www.tldraw.com/
    - title: "JSON Crack"
      description: "最佳的在线 JSON 查看器，用于可视化、格式化和探索 JSON 数据。"
      type: link
      url: https://jsoncrack.com/
    - title: "IPCheck.ing"
      description: "查看我的 IP 地址"
      type: link
      url: https://ipcheck.ing/
    - title: Quick Reference
      description: "方便开发人员查阅技术栈"
      type: link
      url: https://quickref.cn/
    - title: 使用官方在线版 - PushDeer·推送说明
      description: "PushDeer 是一个开源的推送服务，支持多种推送方式"
      type: link
      url: https://www.pushdeer.com/official.html
  Dev/开发资源:
    - title: 软件源 - LinuxMirrors
      description: ""
      type: link
      url: https://linuxmirrors.cn/mirrors/
    - title: Road 2 Coding
      description: ""
      type: link
      url: https://r2coding.com/#/README
    - title: "Kaggle: Your Machine Learning and Data Science Community"
      description: "Kaggle 是一个数据科学竞赛平台，提供数据集、竞赛、教程等资源"
      type: link
      url: https://www.kaggle.com/
  Tech/技术站点:
    - title: V2EX
      description: "V2EX 是一个关于分享和探索创意的社区"
      type: link
      url: https://v2ex.com/
      pinned: true
    - title: HelloGitHub
      description: "分享 GitHub 上有趣、入门级的开源项目"
      type: link
      url: https://hellogithub.com/
      pinned: true
    - title: 少数派 - 高效工作，品质生活
      description: ""
      type: link
      url: https://sspai.com/
    - title: 装备前线 zFrontier - zFrontier 装备前线
      description: ""
      type: link
      url: https://www.zfrontier.com/app/#new
    - title: InfoQ - 促进软件开发及相关领域知识与创新的传播-极客邦
      description: ""
      type: link
      url: https://www.infoq.cn/
    - title: 潮流周刊
      description: ""
      type: link
      url: https://weekly.tw93.fun/
      pinned: true
    - title: APPDO数字生活指南 | 💡互联网/数码/App/羊毛/相机/数字指南
      description: ""
      type: link
      url: https://appdo.xyz/
    - title: 悟空百科
      description: ""
      type: link
      url: https://didiboy0702.gitbook.io/wukongdaily/
    - title: IT豪哥-电脑教程网
      description: ""
      type: link
      url: https://www.ithaoge.cn/
    - title: 零度博客 - 专注分享免费实用软件、AI黑科技、有趣网站及电脑系统相关安装教程！
      description: ""
      type: link
      url: https://www.freedidi.com/
  Product/产品与设计:
    - title: iconfont-阿里巴巴矢量图标库
      description: "阿里巴巴矢量图标库"
      type: link
      url: https://www.iconfont.cn/
    - title: 数字像素 -可视化设计、开发、互动综合服务平台
      description: "可视化设计、开发、互动综合服务平台"
      type: link
      url: https://www.shuzixs.com/#/home/
    - title: emoji表情符号大全
      description: "emoji表情符号大全"
      type: link
      url: https://emoji6.com/emojiall/
    - title: Yesicon - 精选全球高品质、开源、免费的矢量图标库
      description: "精选全球高品质、开源、免费的矢量图标库"
      type: link
      url: https://yesicon.app/
    - title: Navbar Gallery – Navbar Design Inspiration
      description: "导航栏设计灵感"
      type: link
      url: https://www.navbar.gallery/
  Media/流媒体:
    - title: 哔哩哔哩 (゜-゜)つロ 干杯~-bilibili
      description: "中文世界最具影响力的视频平台"
      type: link
      url: https://www.bilibili.com/
      pinned: true
    - title: 爱奇艺-在线视频网站-海量正版高清视频在线观看
      description: "海量正版高清视频在线观看"
      type: link
      url: https://www.iqiyi.com/
    - title: YouTube
      description: "全球最大的视频平台"
      type: link
      url: https://www.youtube.com/
      pinned: true
  Media/影视资源:
    - title: "豆瓣电影"
      description: "中文世界最具影响力的电影评论社区"
      type: "link"
      url: "https://movie.douban.com"
    - title: 观影 GYING
      description: ""
      type: link
      url: https://www.gying.in/
    - title: SeedHub | 影视&动漫分享
      description: ""
      type: link
      url: https://www.seedhub.cc/
    - title: 高清Mp4吧
      description: ""
      type: link
      url: https://www.mp4ba.vip/
    - title: 分享交流下载字幕平台 - SubHD
      description: "分享交流下载字幕平台"
      type: link
      url: https://subhd.tv/
    - title: 片库 - 全网高清影视聚合下载,电影免费在线观看,片库网
      description: ""
      type: link
      url: https://www.pkmp4.com/
    - title: 搜片.com - 搜你想看的影片
      description: ""
      type: link
      url: https://soupian.app/
    - title: 电影剧集 | ZAPRO · 杂铺
      description: ""
      type: link
      url: https://tmioe.com/movie
    - title: 4K电影美剧下载 - HDR杜比视界资源 - 4KHDR世界 - 4KHDR.CN
      description: ""
      type: link
      url: https://www.4khdr.cn/
    - title: awwrated | 你的 Netflix 及 Disney+ 避雷好幫手
      description: ""
      type: link
      url: https://www.awwrated.com/zh-tw/netflix
    - title: 影巢 - 网盘资源搜索
      description: ""
      type: link
      url: https://hdhive.org/
    - title: 磁力熊 - 豆瓣高分电影1080P下载
      description: ""
      type: link
      url: https://www.cilixiong.com/
    - title: 看片狂人 - 防迷路
      description: ""
      type: link
      url: https://kuangren.us/
    - title: 楓林網
      description: "综合视频资源网站"
      type: link
      url: https://imaple8.co/
  Media/动漫资源:
    - title: 蜜柑计划 - Mikan Project
      description: "日本动漫资源分享网站"
      type: link
      url: https://mikanani.me/
      pinned: true
    - title: 動漫花園資源網
      description: "日本动漫资源分享网站"
      type: link
      url: https://dmhy.anoneko.com/
    - title: 異世界動漫
      description: "日本动漫资源分享网站"
      type: link
      url: https://www.ysjdm.net/
    - title: 七色番动漫视频网 - (つェ⊂) 7SeFuN
      description: "日本动漫资源分享网站"
      type: link
      url: https://www.7sefun.top/
    - title: girigiri爱动漫~just a little love~Σ(っ °Д °;)っ∇
      description: "日本动漫资源分享网站"
      type: link
      url: https://anime.girigirilove.com/
    - title: Bangumi 番组计划
      description: "番组计划，日本动漫资料库"
      type: link
      url: https://bangumi.tv/
    - title: ACG.RIP
      description: "ACG.RIP"
      type: link
      url: https://acg.rip/
  Media/漫画二次元:
    - title: mangabz
      description: "日本漫畫,在線漫畫閱讀第一站"
      type: link
      url: https://www.mangabz.com/
    - title: pixiv
      description: "日本插画交流社区"
      type: link
      url: https://www.pixiv.net/
  SaaS:
    - title: flomo
      description: "flomo是一款以卡片笔记为核心的轻量化记录工具，支持多端同步，通过微信输入、多级标签和智能关联功能，帮助用户轻松捕捉灵感并建立知识网络。"
      type: link
      url: https://v.flomoapp.com/mine
      pinned: true
    - title: 微信公众平台
      description: "服务号、公众号、小程序"
      type: link
      url: https://mp.weixin.qq.com/
    - title: 简道云
      description: "国内领先的企业级零代码应用搭建平台"
      type: link
      url: https://www.jiandaoyun.com/
      pinned: true
  Shopping:
    - title: 什么值得买
      description: "什么值得买，值得买"
      type: link
      url: https://www.smzdm.com/
    - title: 淘宝
      description: "淘宝，淘你喜欢"
      type: link
      url: https://www.taobao.com/
    - title: 京东
      description: "京东，多快好省"
      type: link
      url: https://www.jd.com/
  Game:
    - title: Steam
      description: "全球最大的游戏平台"
      type: link
      url: https://store.steampowered.com/
    - title: 杉果游戏
      description: "全方位正版游戏服务平台"
      type: link
      url: https://www.sonkwo.cn/
    - title: MAMEdev.org
      description: "Home of The MAME Project"
      type: link
      url: https://www.mamedev.org/index.php
    - title: Retroroms
      description: ""
      type: link
      url: https://www.retroroms.info/index.php
