# 工具索引文件
# - title: "填写标题"
#     description: "填写描述"
#     type: "link"
#     url: "填写跳转的 url"
#     repo: "如没有，删掉此行"
#     source: "自建" 或 "第三方"

tools:
  - title: "☁️ 云需求顾问"
    description: "智能的云服务配置助手系统，集成大模型能力，支持自然语言需求解析和自动配置清单生成"
    type: "link"
    url: "https://cloudadvisor.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/CloudAdvisor"
    source: "自建"
    
  - title: "DayCraft 智能日报助手"
    description: "告别繁琐的日报撰写，专注于真正的工作。 我们的AI助手帮您整理、记录和生成专业的日报和周报，提高工作效率。"
    type: "link"
    url: "https://daycraft.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/DayCraft"
    source: "自建"
  
  - title: "Markdown 转 Word 工具"
    description: "一个简单易用的 Markdown 转 Word 文档工具，支持多种格式转换和样式定制。"
    type: "link"
    url: "https://md2docx.qingwalashi.cn"
    repo: "https://github.com/qingwalashi/MD2DOCX"
    source: "自建"
    
  - title: "合同金额转换工具"
    description: "快速计算合同金额、税额及生成中文大写金额。"
    type: "link"
    url: "https://amountconvert.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/AmountConvert"
    source: "自建"
  
  - title: "宁波阳光采购平台近期开标信息"
    description: "转发跳转到自建的宁波阳光采购平台近期开标信息网站，每日自动更新近3天的开标信息。"
    type: "link"
    url: "https://nbygcg.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/nbygcg"
    source: "自建"
   
  - title: "订阅到期管理"
    description: "一站式订阅到期管理工具，支持域名、证书、工作安排等各类事项的自动化提醒。通过简单配置，轻松管理所有重要时间节点，让您不再错过任何关键日期。"
    type: "link"
    url: "https://schedule.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/ScheduleAutomation"
    source: "自建"

  - title: "基于天地图的宁波地理数据"
    description: "一个基于天地图与 OpenStreetMap 的可视化小项目，用于展示宁波市不同要素（商圈、医院、学校等）的边界，并支持坐标从 WGS84 转 CGCS2000。"
    type: "link"
    url: "https://ningbohub.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/nignbohub"
    source: "自建"
  
  - title: "项目售前交付成本模型"
    description: "一个用于分析售前阶段时长对项目总交付成本影响的静态网页工具。该工具基于团队配置和时间压力的数学模型，帮助项目管理者优化售前和交付阶段的时间分配。"
    type: "link"
    url: "https://pdo-cost-model.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/pdo-cost-model"
    source: "自建"

  - title: "DeepResearch Web UI"
    description: "Deep Research 是  dzhng/deep-research  的可视化 UI，可以让 AI 根据特定问题联网搜索并自行深挖，并输出研究报告。本项目可以流式传输 AI 的回答来实时反馈，并使用树状结构可视化搜索过程。"
    type: "link"
    url: "https://deep-research.ataw.top/"
    repo: "https://github.com/AnotiaWang/deep-research-web-ui"
    source: "第三方"

  - title: "prompt-optimizer"
    description: "一款提示词优化器，助力于编写高质量的提示词"
    type: "link"
    url: "https://prompt.always200.com/"
    repo: "https://github.com/linshenkx/prompt-optimizer"
    source: "第三方"
