# 工具索引文件
# - title: "填写标题"
#     description: "填写描述"
#     type: "link"
#     url: "填写跳转的 url"
#     repo: "如没有，删掉此行"

tools:
  - title: "个人项目管理-进度看板"
    description: "依托简道云建立的项目进度看板，输入密码后查看"
    type: "link"
    url: "https://trhj7w84un.jiandaoyun.com/dash/683873b564f1c0fc3251192a"

  - title: "个人项目管理-自研成本看板"
    description: "依托简道云建立的项目自研成本看板，输入密码后查看"
    type: "link"
    url: "https://trhj7w84un.jiandaoyun.com/dash/68412d127ec0a5483ab47c7a"
    
  - title: "Markdown 转 Word 工具"
    description: "一个简单易用的 Markdown 转 Word 文档工具，支持多种格式转换和样式定制。"
    type: "link"
    url: "https://md2docx.qingwalashi.cn"
    repo: "https://github.com/qingwalashi/MD2DOCX"
    
  - title: "合同金额转换工具"
    description: "快速计算合同金额、税额及生成中文大写金额。"
    type: "link"
    url: "https://amountconvert.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/AmountConvert"
  
  - title: "宁波阳光采购平台近期开标信息"
    description: "转发跳转到自建的宁波阳光采购平台近期开标信息网站，每日自动更新近3天的开标信息。"
    type: "link"
    url: "https://nbygcg.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/nbygcg"   

  - title: "订阅到期管理"
    description: "一站式订阅到期管理工具，支持域名、证书、工作安排等各类事项的自动化提醒。通过简单配置，轻松管理所有重要时间节点，让您不再错过任何关键日期。"
    type: "link"
    url: "https://schedule.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/ScheduleAutomation"

  - title: "DeepResearch Web UI(fork repo)"
    description: "Deep Research 是  dzhng/deep-research  的可视化 UI，可以让 AI 根据特定问题联网搜索并自行深挖，并输出研究报告。本项目可以流式传输 AI 的回答来实时反馈，并使用树状结构可视化搜索过程。"
    type: "link"
    url: "https://deep-research.qingwalashi.cn/"
    repo: "https://github.com/qingwalashi/deep-research-web-ui"

